name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PVT_KEY }}
          
      - name: Deploy to cPanel
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ${{ secrets.USER_NAME }}@${{ secrets.HOST_IP }} "
            if [ ! -d \"${{ secrets.PATH }}/.git\" ]; then
              echo 'Cloning repository...'
              git clone https://github.com/${{ github.repository }} ${{ secrets.PATH }}
            else
              echo 'Repository already cloned, pulling latest changes...'
              cd ${{ secrets.PATH }} && git pull origin main
            fi
          "
