name: Notify Telegram Channel on Push to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Telegram Channel
        run: |
          curl -X POST "https://api.telegram.org/bot7922464381:AAEAcsaMypwpZUuuPVT3762S9h0TEj-Pim0/sendMessage" \
          -d chat_id=-1002312187017 \
          -d text="🚀 A new push was made to the main branch in repository ${{ github.repository }} by ${{ github.actor }}. Commit message: ${{ github.event.head_commit.message || 'No commit message provided' }}."
