name: Notify Telegram Channel on Push to Main

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Telegram Channel
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL_ID: "-1002312187017"
        run: |
          curl -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
          -d chat_id=$TELEGRAM_CHANNEL_ID \
          -d text="🚀 A new push was made to the main branch in repository ${{ github.repository }} by ${{ github.actor }}. \
Commit message: ${{ github.event.head_commit.message }}."
